name: 'Await checks'
description: 'Await running checks before continuing'
author: 'banst'
branding:
  icon: 'clock'
  color: 'black'
inputs:
  name_pattern:
    description: 'Workflow names pattern (regex)'
    default: '.*'
  github_token:
    description: 'Github token to make api calls'
  include_queue:
    description: 'Inlude queued jobs'
    default: true
  wait_ms:
    description: 'Time to wait between call (in ms)'
    default: 1000
runs:
  using: 'node12'
  main: 'lib/main.js'
